# Generated by Django 3.1.3 on 2020-11-26 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='interests',
            field=models.ManyToManyField(to='user.Interest'),
        ),
    ]
