# Generated by Django 3.1.3 on 2020-12-18 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userinfo_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(default=django.utils.timezone.now, max_length=56),
            preserve_default=False,
        ),
    ]
