# Generated by Django 3.1.3 on 2020-12-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_userinfo_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='match',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='bio',
            field=models.CharField(max_length=56, null=True),
        ),
    ]
